development:
  adapter: postgresql
  database: teamsquad_dev
  host: localhost
  username: xxx
  password: xxx
  encoding: UTF8

test:
  adapter: postgresql
  database: teamsquad_test
  host: localhost
  username: xxx
  password: xxx
  encoding: UTF8

production:
  adapter: postgresql
  database: teamsquad
  host: localhost
  username: xxx
  password: xxx
  encoding: UTF8